### ISSUE TITLE
P1: Project Management focused verification fails from clean-process circular import

### ISSUE THREAD

**Issue by NielPieterse0** [NielPieterse0/kis-mcp#422]
## Parent
#420 post-#406 landed-change live verification remediation.

## Reproduction
Current live/main revision: `f2f765739bad137de8a855ecdea1198e495f85a0`.

A clean locked-environment invocation:
`uv run --frozen python -m pytest -q tests/workflows/project_management/test_enhanced_tools.py`

fails during collection with:
`ImportError: cannot import name 'implementation_trace_from_json' from partially initialized module 'kis_mcp.workflows.project_management'`

Observed cycle:
`project_management.__init__ -> project_management.descriptors -> capabilities.__init__ -> capabilities.execution -> workflows.merge_queue -> workflows.project_management`

This also breaks the combined post-#406 focused verification matrix. The #406 adapter/service tests themselves remain green and live pagination behavior is correct, but one focused module touched by PR #414 cannot currently be collected from a clean process.

Historical #271 fixed a related import-order defect in an earlier architecture. Do not assume this is the same implementation path; treat #271 as lineage/evidence only unless root-cause comparison proves otherwise.

## Acceptance
- Reproduce from a clean Python process with no prior KIS imports.
- Remove or restructure the current circular dependency without weakening capability/workflow boundaries.
- `tests/workflows/project_management/test_enhanced_tools.py` collects and passes independently.
- Add regression coverage for clean-process/import-order behavior of the affected package boundary.
- Re-run the #406 focused adapter/service/enhanced-tools verification set successfully on current main plus the fix.
- Preserve current live Work Management pagination semantics and exact-target/broad-read separation.
